import streamlit as st
from datetime import datetime
import pandas as pd
from fpdf import FPDF
import io
import base64
from PIL import Image
import os

# Configuración de la página
st.set_page_config(
    page_title="BIAS - Behavioral Intelligence Analysis System",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Diccionarios para traducción
translations = {
    "Español": {
        "app_title": "BIAS - Sistema de Análisis de Inteligencia Conductual",
        "welcome": "Bienvenido/a al Sistema de Análisis de Inteligencia Conductual",
        "login": "Iniciar Sesión",
        "username": "Usuario",
        "password": "Contraseña",
        "login_button": "Entrar",
        "language": "Idioma",
        "logout": "Cerrar Sesión",
        "profile_section": "Perfil de evaluación",
        "name": "Nombre completo",
        "id_number": "Número de identificación",
        "age": "Edad",
        "gender": "Género",
        "male": "Masculino",
        "female": "Femenino",
        "other": "Otro",
        "education": "Nivel educativo",
        "primary": "Primaria",
        "secondary": "Secundaria",
        "university": "Universidad",
        "postgraduate": "Postgrado",
        "none": "Sin estudios",
        "substances": "Consumo de sustancias",
        "alcohol": "Alcohol",
        "tobacco": "Tabaco",
        "recreational": "Drogas recreativas",
        "cocaine": "Cocaína",
        "heroin": "Heroína",
        "none_substance": "Ninguna",
        "criminal_record": "Antecedentes penales",
        "theft": "Robo",
        "gender_violence": "Violencia de género",
        "homicide": "Homicidio",
        "terrorism": "Terrorismo",
         "hate_speech": "Discurso de odio",
        "online_radicalization": "Radicalización en línea",
        "travel_attempts": "Intentos de viaje a zonas de conflicto",
        "financial_support": "Apoyo financiero a grupos extremistas",
        "possession_weapons": "Posesión de armas",
        "attack_planning": "Planificación de ataques",
        "recruitment": "Reclutamiento de nuevos miembros",
        "propaganda_consumption": "Consumo de propaganda extremista",
        "isolation": "Aislamiento social",
        "identity_crisis": "Crisis de identidad",
        "none_criminal": "Ninguno",
        "personality_traits": "Rasgos de personalidad",
        "paranoid": "Paranoide",
        "antisocial": "Antisocial",
        "sadomasochistic": "Sadomasoquista",
        "impulsive": "Impulsivo",
        "unstable": "Emocionalmente inestable",
        "dependent": "Dependiente",
        "avoidant": "Evitativo",
         "narcissistic": "Narcisista",
        "histrionic": "Histriónico",
        "passive_aggressive": "Pasivo-agresivo",
        "schizoid": "Esquizoide",
        "obsessive": "Obcecado con el control",
        "none_traits": "Ninguno significativo",
        "submit": "Enviar evaluación",
        "results_section": "Resultados de la evaluación",
        "risk_level": "Nivel de riesgo:",
        "high": "ALTO",
        "moderate": "MODERADO",
        "low": "BAJO",
        "evaluation_date": "Fecha de evaluación:",
        "generate_report": "Generar informe",
        "download_report": "Descargar Informe",
        "download_detailed": "Descargar Informe Detallado",
        "login_error": "Usuario o contraseña incorrectos",
        "field_required": "Este campo es obligatorio",
        "results_info": "Tras enviar la evaluación, aquí se mostrarán los resultados del análisis de riesgo.",
        "recommendations": "Recomendaciones institucionales",
        "therapy_recs": "Recomendaciones Terapéuticas",
        "medication_recs": "Recomendaciones Farmacológicas",
        "reintegration_recs": "Terapias de Reinserción",
        "prevention_recs": "Medidas de Prevención",
        "urgent_measures": "Medidas de Urgencia",
        "explanation": "Explicación del Nivel de Riesgo",
        "high_explanation": "El sujeto presenta múltiples factores de riesgo significativos que sugieren una alta probabilidad de radicalización violenta. Se recomienda intervención inmediata y monitoreo constante.",
        "moderate_explanation": "El sujeto presenta algunos factores de riesgo relevantes que requieren atención y seguimiento. Se recomienda intervención preventiva y evaluación periódica.",
        "low_explanation": "El sujeto presenta pocos factores de riesgo. Se recomienda seguimiento rutinario y medidas preventivas básicas.",
        "scoring_report": "Informe Detallado de Puntuación",
        "detailed_scoring": "Puntuación Detallada",
        "total_risk_score": "Puntuación total de riesgo",
        "education_score": "Puntuación nivel educativo",
        "substances_score": "Puntuación consumo de sustancias",
        "criminal_score": "Puntuación antecedentes penales",
        "personality_score": "Puntuación rasgos de personalidad",
        "diagnosis_list": "Diagnósticos previos",
         "ptsd": "Trastorno de estrés postraumático (TEPT)",
        "bpd": "Trastorno límite de la personalidad (TLP)",
        "bipolar": "Trastorno bipolar",
        "schizophrenia": "Esquizofrenia",
        "major_depression": "Depresión mayor recurrente",
        "ocd": "Trastorno obsesivo-compulsivo (TOC)",
        "gad": "Trastorno de ansiedad generalizada (TAG)",
        "panic_disorder": "Trastorno de pánico",
        "social_phobia": "Fobia social",
        "conduct_disorder": "Trastorno de la conducta",
        "previous_therapies": "Terapias previas",
        "therapy_date": "Fecha de inicio de terapia",
        "select_date": "Seleccionar fecha",
        "alarm_date": "Fecha de señales de alarma",
        "interest_profile": "Motivo de interés",
        "family_extremism": "Antecedentes de extremismo familiar",
        "upload_photo": "Subir fotografía del sujeto",
        "upload_button": "Subir imagen",
        "photo_requirements": "La fotografía debe ser tipo carnet con fondo blanco",
         "clinical_history": "Historial Clínico",
        "psychological_profile": "Perfil Psicológico",
        "additional_comments": "Comentarios Adicionales"
    },
    "English": {
        "app_title": "BIAS - Behavioral Intelligence Analysis System",
        "welcome": "Welcome to the Behavioral Intelligence Analysis System",
        "login": "Login",
        "username": "Username",
        "password": "Password",
        "login_button": "Enter",
        "language": "Language",
        "logout": "Logout",
        "profile_section": "Evaluation Profile",
        "name": "Full Name",
        "id_number": "ID Number",
        "age": "Age",
        "gender": "Gender",
        "male": "Male",
        "female": "Female",
        "other": "Other",
        "education": "Education Level",
        "primary": "Primary",
        "secondary": "Secondary",
        "university": "University",
        "postgraduate": "Postgraduate",
        "none": "No Education",
        "substances": "Substance Use",
        "alcohol": "Alcohol",
        "tobacco": "Tobacco",
        "recreational": "Recreational Drugs",
        "cocaine": "Cocaine",
        "heroin": "Heroin",
        "none_substance": "None",
        "criminal_record": "Criminal Record",
        "theft": "Theft",
        "gender_violence": "Gender Violence",
        "homicide": "Homicide",
        "terrorism": "Terrorism",
        "hate_speech": "Hate speech",
        "online_radicalization": "Online radicalization",
        "travel_attempts": "Travel attempts to conflict zones",
        "financial_support": "Financial support to extremist groups",
        "possession_weapons": "Possession of weapons",
        "attack_planning": "Attack planning",
        "recruitment": "Recruitment of new members",
        "propaganda_consumption": "Consumption of extremist propaganda",
        "isolation": "Social isolation",
        "identity_crisis": "Identity crisis",
        "none_criminal": "None",
        "personality_traits": "Personality Traits",
        "paranoid": "Paranoid",
        "antisocial": "Antisocial",
        "sadomasochistic": "Sadomasochistic",
        "impulsive": "Impulsive",
        "unstable": "Emotionally Unstable",
        "dependent": "Dependent",
        "avoidant": "Avoidant",
        "narcissistic": "Narcissistic",
        "histrionic": "Histrionic",
        "passive_aggressive": "Passive-aggressive",
        "schizoid": "Schizoid",
        "obsessive": "Obsessive",
        "none_traits": "No Significant Traits",
        "submit": "Submit Evaluation",
        "results_section": "Evaluation Results",
        "risk_level": "Risk Level:",
        "high": "HIGH",
        "moderate": "MODERATE",
        "low": "LOW",
        "evaluation_date": "Evaluation Date:",
        "generate_report": "Generate Report",
        "download_report": "Download Report",
        "download_detailed": "Download Detailed Report",
        "login_error": "Incorrect username or password",
        "field_required": "This field is required",
        "results_info": "After submitting the evaluation, the risk analysis results will be displayed here.",
        "recommendations": "Institutional Recommendations",
        "therapy_recs": "Therapeutic Recommendations",
        "medication_recs": "Pharmacological Recommendations",
        "reintegration_recs": "Reintegration Therapies",
        "prevention_recs": "Preventive Measures",
        "urgent_measures": "Urgent Measures",
        "explanation": "Risk Level Explanation",
        "high_explanation": "The subject presents multiple significant risk factors that suggest a high probability of violent radicalization. Immediate intervention and constant monitoring are recommended.",
        "moderate_explanation": "The subject presents some relevant risk factors that require attention and follow-up. Preventive intervention and periodic evaluation are recommended.",
        "low_explanation": "The subject presents few risk factors. Routine follow-up and basic preventive measures are recommended.",
        "scoring_report": "Detailed Scoring Report",
        "detailed_scoring": "Detailed Scoring",
        "total_risk_score": "Total risk score",
        "education_score": "Education level score",
        "substances_score": "Substance use score",
        "criminal_score": "Criminal record score",
        "personality_score": "Personality traits score",
        "diagnosis_list": "Previous diagnoses",
        "ptsd": "Post-traumatic stress disorder (PTSD)",
        "bpd": "Borderline personality disorder (BPD)",
        "bipolar": "Bipolar disorder",
        "schizophrenia": "Schizophrenia",
        "major_depression": "Recurrent major depression",
        "ocd": "Obsessive-compulsive disorder (OCD)",
        "gad": "Generalized anxiety disorder (GAD)",
        "panic_disorder": "Panic disorder",
        "social_phobia": "Social phobia",
        "conduct_disorder": "Conduct disorder",
        "previous_therapies": "Previous therapies",
        "therapy_date": "Therapy start date",
        "select_date": "Select date",
        "alarm_date": "Date of warning signs",
        "interest_profile": "Reason for interest",
        "family_extremism": "Family history of extremism",
        "upload_photo": "Upload subject photo",
        "upload_button": "Upload image",
        "photo_requirements": "Photo must be ID-type with white background",
        "clinical_history": "Clinical History",
        "psychological_profile": "Psychological Profile",
        "additional_comments": "Additional Comments"
    },
    "العربية": {
        "app_title": "BIAS - نظام تحليل الذكاء السلوكي",
        "welcome": "مرحبًا بك في نظام تحليل الذكاء السلوكي",
        "login": "تسجيل الدخول",
        "username": "اسم المستخدم",
        "password": "كلمة المرور",
        "login_button": "دخول",
        "language": "اللغة",
        "logout": "تسجيل الخروج",
        "profile_section": "ملف التقييم",
        "name": "الاسم الكامل",
        "id_number": "رقم الهوية",
        "age": "العمر",
        "gender": "الجنس",
        "male": "ذكر",
        "female": "أنثى",
        "other": "آخر",
        "education": "المستوى التعليمي",
        "primary": "ابتدائي",
        "secondary": "ثانوي",
        "university": "جامعي",
        "postgraduate": "دراسات عليا",
        "none": "بدون تعليم",
        "substances": "تعاطي المواد",
        "alcohol": "الكحول",
        "tobacco": "التبغ",
        "recreational": "المخدرات الترفيهية",
        "cocaine": "الكوكايين",
        "heroin": "الهيروين",
        "none_substance": "لا شيء",
        "criminal_record": "السجل الجنائي",
        "theft": "سرقة",
        "gender_violence": "عنف على أساس الجنس",
        "homicide": "قتل",
        "terrorism": "إرهاب",
        "hate_speech": "خطاب الكراهية",
        "online_radicalization": "التطرف عبر الإنترنت",
        "travel_attempts": "محاولات السفر إلى مناطق النزاع",
        "financial_support": "دعم مالي للجماعات المتطرفة",
        "possession_weapons": "حيازة أسلحة",
        "attack_planning": "التخطيط للهجمات",
        "recruitment": "تجنيد أعضاء جدد",
        "propaganda_consumption": "استهلاك الدعاية المتطرفة",
        "isolation": "عزلة اجتماعية",
        "identity_crisis": "أزمة هوية",
        "none_criminal": "لا شيء",
        "personality_traits": "سمات الشخصية",
        "paranoid": "جنوني",
        "antisocial": "معادي للمجتمع",
        "sadomasochistic": "سادي مازوخي",
        "impulsive": "متهور",
        "unstable": "غير مستقر عاطفياً",
        "dependent": "اعتمادي",
        "avoidant": "تجنبي",
        "narcissistic": "النرجسي",
        "histrionic": "هستيري",
        "passive_aggressive": "سلبي عدواني",
        "schizoid": "شيزويد",
        "obsessive": "مهووس",
        "none_traits": "لا توجد سمات مهمة",
        "submit": "إرسال التقييم",
        "results_section": "نتائج التقييم",
        "risk_level": "مستوى الخطر:",
        "high": "عالي",
        "moderate": "متوسط",
        "low": "منخفض",
        "evaluation_date": "تاريخ التقييم:",
        "generate_report": "إنشاء تقرير",
        "download_report": "تنزيل التقرير",
        "download_detailed": "تنزيل التقرير المفصل",
        "login_error": "اسم المستخدم أو كلمة المرور غير صحيحة",
        "field_required": "هذا الحقل مطلوب",
        "results_info": "بعد إرسال التقييم، ستظهر هنا نتائج تحليل المخاطر.",
        "recommendations": "التوصيات المؤسسية",
        "therapy_recs": "التوصيات العلاجية",
        "medication_recs": "التوصيات الدوائية",
        "reintegration_recs": "علاجات إعادة الدمج",
        "prevention_recs": "تدابير وقائية",
        "urgent_measures": "تدابير عاجلة",
        "explanation": "شرح مستوى الخطر",
        "high_explanation": "يظهر الشخص عوامل خطر متعددة مهمة تشير إلى احتمالية عالية للتطرف العنيف. يوصى بالتدخل الفوري والمراقبة المستمرة.",
        "moderate_explanation": "يظهر الشخص بعض عوامل الخطر ذات الصلة التي تتطلب اهتمامًا ومتابعة. يوصى بالتدخل الوقائي والتقييم الدوري.",
        "low_explanation": "يظهر الشخص عدد قليل من عوامل الخطر. يوصى بالمتابعة الروتينية والتدابير الوقائية الأساسية.",
        "scoring_report": "تقرير التسجيل المفصل",
        "detailed_scoring": "التسجيل المفصل",
        "total_risk_score": "مجموع نقاط الخطر",
        "education_score": "نقاط المستوى التعليمي",
        "substances_score": "نقاط تعاطي المواد",
        "criminal_score": "نقاط السجل الجنائي",
        "personality_score": "نقاط سمات الشخصية",
        "diagnosis_list": "التشخيصات السابقة",
        "ptsd": "اضطراب ما بعد الصدمة",
        "bpd": "اضطراب الشخصية الحدية",
        "bipolar": "اضطراب ثنائي القطب",
        "schizophrenia": "الفصام",
        "major_depression": "الاكتئاب الشديد المتكرر",
        "ocd": "اضطراب الوسواس القهري",
        "gad": "اضطراب القلق العام",
        "panic_disorder": "اضطراب الهلع",
        "social_phobia": "الرهاب الاجتماعي",
        "conduct_disorder": "اضطراب السلوك",
        "previous_therapies": "العلاجات السابقة",
        "therapy_date": "تاريخ بدء العلاج",
        "select_date": "اختر التاريخ",
        "alarm_date": "تاريخ علامات التحذير",
        "interest_profile": "سبب الاهتمام",
        "family_extremism": "التاريخ العائلي للتطرف",
        "upload_photo": "تحميل صورة الشخص",
        "upload_button": "تحميل الصورة",
        "photo_requirements": "يجب أن تكون الصورة من نوع الهوية بخلفية بيضاء",
        "clinical_history": "السجل السريري",
        "psychological_profile": "الملف النفسي",
        "additional_comments": "تعليقات إضافية"
    },
    "Français": {
        "app_title": "BIAS - Système d'Analyse de l'Intelligence Comportementale",
        "welcome": "Bienvenue au Système d'Analyse de l'Intelligence Comportementale",
        "login": "Connexion",
        "username": "Nom d'utilisateur",
        "password": "Mot de passe",
        "login_button": "Entrer",
        "language": "Langue",
        "logout": "Déconnexion",
        "profile_section": "Profil d'évaluation",
        "name": "Nom complet",
        "id_number": "Numéro d'identification",
        "age": "Âge",
        "gender": "Genre",
        "male": "Masculin",
        "female": "Féminin",
        "other": "Autre",
        "education": "Niveau d'éducation",
        "primary": "Primaire",
        "secondary": "Secondaire",
        "university": "Universitaire",
        "postgraduate": "Postuniversitaire",
        "none": "Sans éducation",
        "substances": "Consommation de substances",
        "alcohol": "Alcool",
        "tobacco": "Tabac",
        "recreational": "Drogues récréatives",
        "cocaine": "Cocaïne",
        "heroin": "Héroïne",
        "none_substance": "Aucune",
        "criminal_record": "Antécédents criminels",
        "theft": "Vol",
        "gender_violence": "Violence basée sur le genre",
        "homicide": "Homicide",
        "terrorism": "Terrorisme",
        "hate_speech": "Discours de haine",
        "online_radicalization": "Radicalisation en ligne",
        "travel_attempts": "Tentatives de voyage vers des zones de conflit",
        "financial_support": "Soutien financier aux groupes extrémistes",
        "possession_weapons": "Possession d'armes",
        "attack_planning": "Planification d'attaques",
        "recruitment": "Recrutement de nouveaux membres",
        "propaganda_consumption": "Consommation de propagande extrémiste",
        "isolation": "Isolement social",
        "identity_crisis": "Crise d'identité",
        "none_criminal": "Aucun",
        "personality_traits": "Traits de personnalité",
        "paranoid": "Paranoïaque",
        "antisocial": "Antisocial",
        "sadomasochistic": "Sadomasochiste",
        "impulsive": "Impulsif",
        "unstable": "Émotionnellement instable",
        "dependent": "Dépendant",
        "avoidant": "Évitant",
        "narcissistic": "Narcissique",
        "histrionic": "Histrionique",
        "passive_aggressive": "Passif-agressif",
        "schizoid": "Schizoïde",
        "obsessive": "Obsessionnel",
        "none_traits": "Aucun trait significatif",
        "submit": "Soumettre l'évaluation",
        "results_section": "Résultats de l'évaluation",
        "risk_level": "Niveau de risque:",
        "high": "ÉLEVÉ",
        "moderate": "MODÉRÉ",
        "low": "FAIBLE",
        "evaluation_date": "Date d'évaluation:",
        "generate_report": "Générer le rapport",
        "download_report": "Télécharger le rapport",
        "download_detailed": "Télécharger le rapport détaillé",
        "login_error": "Nom d'utilisateur ou mot de passe incorrect",
        "field_required": "Ce champ est obligatoire",
        "results_info": "Après avoir soumis l'évaluation, les résultats de l'analyse des risques seront affichés ici.",
        "recommendations": "Recommandations institutionnelles",
        "therapy_recs": "Recommandations thérapeutiques",
        "medication_recs": "Recommandations pharmacologiques",
        "reintegration_recs": "Thérapies de réintégration",
        "prevention_recs": "Mesures préventives",
        "urgent_measures": "Mesures urgentes",
        "explanation": "Explication du niveau de risque",
        "high_explanation": "Le sujet présente de multiples facteurs de risque significatifs qui suggèrent une forte probabilité de radicalisation violente. Une intervention immédiate et une surveillance constante sont recommandées.",
        "moderate_explanation": "Le sujet présente certains facteurs de risque pertinents qui nécessitent attention et suivi. Une intervention préventive et une évaluation périodique sont recommandées.",
        "low_explanation": "Le sujet présente peu de facteurs de risque. Un suivi de routine et des mesures préventives de base sont recommandés.",
        "scoring_report": "Rapport de score détaillé",
        "detailed_scoring": "Score détaillé",
        "total_risk_score": "Score de risque total",
        "education_score": "Score du niveau d'éducation",
        "substances_score": "Score de la consommation de substances",
        "criminal_score": "Score des antécédents criminels",
        "personality_score": "Score des traits de personnalité",
        "diagnosis_list": "Diagnostiques précédents",
        "ptsd": "Trouble de stress post-traumatique (TSPT)",
        "bpd": "Trouble de la personnalité limite (TPL)",
        "bipolar": "Trouble bipolaire",
        "schizophrenia": "Schizophrénie",
        "major_depression": "Dépression majeure récurrente",
        "ocd": "Trouble obsessionnel-compulsif (TOC)",
        "gad": "Trouble d'anxiété généralisée (TAG)",
        "panic_disorder": "Trouble panique",
        "social_phobia": "Phobie sociale",
        "conduct_disorder": "Trouble des conduites",
        "previous_therapies": "Thérapies précédentes",
        "therapy_date": "Date de début de la thérapie",
        "select_date": "Sélectionner la date",
        "alarm_date": "Date des signes d'alerte",
        "interest_profile": "Motif d'intérêt",
        "family_extremism": "Antécédents d'extrémisme familial",
        "upload_photo": "Télécharger la photo du sujet",
        "upload_button": "Télécharger l'image",
        "photo_requirements": "La photo doit être de type identité avec un fond blanc",
        "clinical_history": "Antécédents cliniques",
        "psychological_profile": "Profil psychologique",
        "additional_comments": "Commentaires additionnels"
    }
}

# Elementos adicionales para las listas
additional_terrorism_antecedents = [
    "hate_speech",
    "online_radicalization",
    "travel_attempts",
    "financial_support",
    "possession_weapons",
    "attack_planning",
    "recruitment",
    "propaganda_consumption",
    "isolation",
    "identity_crisis"
]

additional_mental_health_traits = [
    "ptsd",
    "bpd",
    "bipolar",
    "schizophrenia",
    "major_depression",
    "ocd",
    "gad",
    "panic_disorder",
    "social_phobia",
    "conduct_disorder"
]

additional_personality_traits = [
    "narcissistic",
    "histrionic",
    "passive_aggressive",
    "schizoid",
    "obsessive"
]

def main():
    st.title(translations["Español"]["app_title"])

    # Autenticación básica
    username = st.text_input(translations["Español"]["username"])
    password = st.text_input(translations["Español"]["password"], type="password")

    if st.button(translations["Español"]["login_button"]):
        if username and password:  # Aquí deberías validar contra una base de datos real
            st.success(translations["Español"]["welcome"] + f", {username}!")

            # Sección de perfil de evaluación
            with st.container():
                st.header(translations["Español"]["profile_section"])
                col1, col2, col3 = st.columns(3)
                with col1:
                    name = st.text_input(translations["Español"]["name"])
                    id_number = st.text_input(translations["Español"]["id_number"])
                    age = st.number_input(translations["Español"]["age"], min_value=0, max_value=120, value=18)
                    gender = st.selectbox(translations["Español"]["gender"], [translations["Español"]["male"], translations["Español"]["female"], translations["Español"]["other"]])
                    education = st.selectbox(translations["Español"]["education"], [translations["Español"]["primary"], translations["Español"]["secondary"], translations["Español"]["university"], translations["Español"]["postgraduate"], translations["Español"]["none"]])
                with col2:
                    substances = st.multiselect(translations["Español"]["substances"], [translations["Español"]["alcohol"], translations["Español"]["tobacco"], translations["Español"]["recreational"], translations["Español"]["cocaine"], translations["Español"]["heroin"], translations["Español"]["none_substance"]])
                    criminal_record = st.multiselect(translations["Español"]["criminal_record"], [translations["Español"]["theft"], translations["Español"]["gender_violence"], translations["Español"]["homicide"], translations["Español"]["terrorism"], translations["Español"]["none_criminal"]] + [translations["Español"][item] for item in additional_terrorism_antecedents])  # Añado aquí los antecedentes
                    personality_traits = st.multiselect(translations["Español"]["personality_traits"], [translations["Español"]["paranoid"], translations["Español"]["antisocial"], translations["Español"]["sadomasochistic"], translations["Español"]["impulsive"], translations["Español"]["unstable"], translations["Español"]["dependent"], translations["Español"]["avoidant"], translations["Español"]["none_traits"]] + [translations["Español"][item] for item in additional_personality_traits])  # Añado aquí los rasgos
                with col3:
                    diagnosis_list = st.multiselect(translations["Español"]["diagnosis_list"], [translations["Español"][item] for item in additional_mental_health_traits]) # Añado aquí los diagnosticos
                    previous_therapies = st.text_input(translations["Español"]["previous_therapies"])
                    therapy_date = st.date_input(translations["Español"]["therapy_date"], datetime.now())
                    alarm_date = st.date_input(translations["Español"]["alarm_date"], datetime.now()).year  # Extraigo solo el año
                    st.write(f"Año de señales de alarma: {alarm_date}")

                st.header("Información Adicional")
                col4, col5, col6 = st.columns(3)
                with col4:
                    clinical_history = st.text_area(translations["Español"]["clinical_history"])
                with col5:
                    psychological_profile = st.text_area(translations["Español"]["psychological_profile"])
                with col6:
                    additional_comments = st.text_area(translations["Español"]["additional_comments"])

            if st.button(translations["Español"]["submit"]):
                # Lógica para generar informes
                if username == "demo_bias":
                    generate_generic_report(name, id_number, age, gender, education, substances, criminal_record, personality_traits, diagnosis_list, previous_therapies, therapy_date, alarm_date, clinical_history, psychological_profile, additional_comments)
                elif username in ["JuanCarlos_bias", "Cristina_bias"]:
                    generate_generic_report(name, id_number, age, gender, education, substances, criminal_record, personality_traits, diagnosis_list, previous_therapies, therapy_date, alarm_date,clinical_history, psychological_profile, additional_comments)
                    generate_director_report(name, id_number, age, gender, education, substances, criminal_record, personality_traits, diagnosis_list, previous_therapies, therapy_date, alarm_date,clinical_history, psychological_profile, additional_comments)
                else:
                    st.warning("No se puede generar el informe para este usuario.")
        else:
            st.error(translations["Español"]["login_error"])

def generate_generic_report(name, id_number, age, gender, education, substances, criminal_record, personality_traits, diagnosis_list, previous_therapies, therapy_date, alarm_date, clinical_history, psychological_profile, additional_comments):
    # Aquí iría la lógica para generar el informe genérico
    st.info("Generando informe genérico...")
    st.write("Datos del sujeto:", name, id_number, age, gender, education, substances, criminal_record, personality_traits, diagnosis_list, previous_therapies, therapy_date, alarm_date, clinical_history, psychological_profile, additional_comments)
    st.write("Explicaciones detalladas de Recomendaciones institucionales (por qué se han elegido éstas)")
   # Aquí iría la lógica para los gráficos
    st.write("Gráficos con: urgencia de actuación y estudio de probabilidad de radicalización o atentado.")
    # Aquí deberías usar librerías como matplotlib o plotly para generar los gráficos
    # y luego insertarlos en el informe

def generate_director_report(name, id_number, age, gender, education, substances, criminal_record, personality_traits, diagnosis_list, previous_therapies, therapy_date, alarm_date, clinical_history, psychological_profile, additional_comments):
    # Aquí iría la lógica para generar el informe para dirección
    st.info("Generando informe para dirección...")
    # Incluir todo lo del informe genérico
    st.write("Datos del sujeto:", name, id_number, age, gender, education, substances, criminal_record, personality_traits, diagnosis_list, previous_therapies, therapy_date, alarm_date, clinical_history, psychological_profile, additional_comments)
    st.write("Explicaciones detalladas de Recomendaciones institucionales (por qué se han elegido éstas)")
   # Aquí iría la lógica para los gráficos
    st.write("Gráficos con: urgencia de actuación y estudio de probabilidad de radicalización o atentado.")
    # Incluir el sistema de puntuación
    st.write("Sistema de puntuación utilizado para tomar todas estas decisiones.")

if __name__ == "__main__":
    main()
